@startuml ERD
entity "User" as user {
  + A single user of the website.
  ==
  + _id : ObjectId <<generated>>
  ..
  + name : string
  ..
  + email : string
  ..
  + password : string <<hashed>>
  ..
  + emailVerified : boolean
}
entity "Task" as task {
  + A single task.
  ==
  + _id : ObjectId <<generated>>
  ..
  + user : ObjectId
  ..
  + name : string
  ..
  + startTime : number
  ..
  + endTime : number
  ..
  + location : [ number, number ] 
}
note "There are many tasks per user but there is only one user per task" as n1
n1 .. user
n1 .. task 
user ||.right.o{ task
@enduml