@startuml
(*) --> "Go to website"
If "Has account" then
    --> [No] "Register new account"
    If "Email exists" then
        --> [No] "Create new account"
        --> "Try logging in"
    else
        -left-> [Yes] "Try another email"
    endif
else
    --> [Yes] "Try logging in"
    If "Remembers password" then
        --> [No] "Request Password Reset"
        --> "Send password reset email"
        --> "Reset password after link in email is clicked"
    else
        --> [Yes] "Authenticate"
        --> (*)
    endif
endif
@enduml