import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  textInput: {
    borderWidth: 2,
    borderColor: '#CCCCCC',
    borderRadius: 4,
    paddingVertical: 10,
    paddingHorizontal: 10,
    marginTop: 4,
    marginBottom: 18,
    minWidth: '80%',
    maxWidth: '80%',
  },
  text: {
    textAlign: 'left',
    fontSize: 18,
    fontFamily: 'Inter-Bold',
  },
  topText: {
    textAlign: 'left',
    fontSize: 18,
    fontFamily: 'Inter-Bold',
    marginBottom: 50,
  },
  smallText: {
    textAlign: 'left',
    fontSize: 14,
    fontFamily: 'Inter-Bold',
    marginTop: 18,
  },
  button: {
    fontFamily: 'Inter-Bold',
    marginVertical: 4,
    paddingVertical: 11,
    paddingHorizontal: 0,
    borderWidth: 2,
    borderColor: '#9DA1FF',
    borderRadius: 4,
    backgroundColor: '#9DA1FF',
    color: 'white',
    textAlign: 'center',
    fontSize: 16,
    overflow: 'hidden',
  },
  cancel: {
    fontFamily: 'Inter-Bold',
    marginVertical: 4,
    paddingVertical: 11,
    paddingHorizontal: 0,
    borderWidth: 2,
    borderColor: '#FF9D9D',
    borderRadius: 4,
    backgroundColor: '#FF9D9D',
    color: 'white',
    textAlign: 'center',
    fontSize: 16,
    overflow: 'hidden',
  },
  graybox: {
    fontFamily: 'Inter-Bold',
    marginVertical: 4,
    paddingVertical: 11,
    paddingHorizontal: 0,
    borderWidth: 2,
    borderColor: '#CCCCCC',
    borderRadius: 4,
    backgroundColor: '#CCCCCC',
    color: 'white',
    textAlign: 'center',
    fontSize: 16,
    overflow: 'hidden',
  },
});

export { styles }